[package]
name = "textcase"
version = "0.1.0"
description = "Simple, multilingual solution for capitalization formatting"
entrypoint = "src/lib.typ"
license = "MIT-0"
authors = ["Maycon F. Melo <@mayconfmelo>"]
categories = [ "languages", "utility" ]
keywords = [ "textcase", "text case", "sentence case", "title case" ]
repository = "https://github.com/mayconfmelo/textcase"
exclude = [
  "dev/",
  "tests/",
  "docs/",
  "scripts/",
  ".git",
  ".github",
  ".gitignore",
  "justfile",
  "manual.typ"
]