[package]
name = "plugin"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
textcase = "0.3.0"

wasm-minimal-protocol = "0.2.0"

serde = { version = "1", features = ["derive"] }
ciborium = "0.2"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
